GET http://localhost/php-api-rest/api/v1/employers.php
Accept: application/json

### POST request to create a new user
POST http://localhost/php-api-rest/api/v1/employers.php
Content-Type: application/json

{
    "name": "Ezequiel",
    "email": "edson@prueba.com",
    "age": 25,
    "designation": "frontend developer"
}





### PUT request to update a user
PUT http://localhost/php-api-rest/api/v1/employers.php
Content-Type: application/json

{
  "id": 15,
  "name": "edson",
  "email": "edson@devcloud.com.edu",
  "age": 26,
  "designation": "backend developer"
}


### DELETE request to delete a user
DELETE http://localhost/php-api-rest/api/v1/employers.php?id=14
Accept: application/json
